[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.17"
optimizer_runs = 200
fs_permissions = [{ access = true, path = "./script/fs/"},{ access = "read", path = "./"}]


[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
polygon = "${POLYGON_RPC}"
goerli = "${GOERLI_RPC}"
mumbai= "${MUMBAI_RPC}"
bnbtestnet= "https://bsc-dataseed.binance.org/"
shibuya = "https://evm.shibuya.astar.network"
astar = "https://evm.astar.network"

[etherscan]
mumbai = { key = "${ETHERSCAN_POLYGON_KEY}", chain=80001 }
polygon = { key = "${ETHERSCAN_POLYGON_KEY}", chain=137 }
goerli = { key = "${ETHERSCAN_MAINNET_KEY}", chain=5 }
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}", chain=1 }
bnbtestnet = {key = "${ETHERSCAN_BNB_KEY}", chain=56}